server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Eureka server does not need to connect to itself
    fetch-registry: false # Eureka server does not need to fetch other services
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #Default zone for Eureka server for other services to register
