spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"
  kafka:
    bootstrap-servers: localhost:29092
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017
      username: admin
      password: admin123
      authentication-database: admin
      port: 27017
      host: localhost
      database: test-mongodb